### ISSUE TITLE
[BUG] after new update

### ISSUE THREAD

**Issue by Winky1st** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#37]
**Describe the bug**
After update to latest today release - v0.3.8-17-gf9c05933, screen on the pad is black

**To Reproduce**
1. Go to 'update'
2. Click on 'update klipperscreen v0.3.8-17-gf9c05933'
5. added : I am using red color theme and boot-up screen it is visible. Only once it has finished loading....the screen goes back to blk.

**Comment by CaryBab** [comment]
I also did an update this morning with the same results.  And now trying to fix it, I've lost all communication to it, and will have to rebuild it from scratch.

**Comment by Winky1st** [comment]
imho - wait... Cyril for sure will fix it! Klipper is perfectly running it is only related to the screen. do not rebuild...wait and all will be fixed soon

**Comment by CaryBab** [comment]
Unfortunately I already screwed the pooch.  I tried doing something stupid, so now I'm rebuilding from scratch.  Its good practice anyway.  But you're right the screen still does not work after the rebuild

**Comment by Winky1st** [comment]
Just wait it will.
Cyril for sure will fix it as soon as he see it.
Just update it once you see the new release on machine update page. cheers

**Comment by cpasoft** [comment]
While Cyril fix it out, you can quickly roll back the version by logging in the printer via the console and doing:
First, go to Kliperscreen folder:
cd KlipperScreen
And then roll back
git checkout b7b3148

`cd KlipperScreen
git checkout b7b3148`

**Comment by Guilouz** [comment]
Should be fixed with last commit.

**Comment by cpasoft** [comment]
Confirmed. The last 0.3.8-21 is fixed.

**Comment by Winky1st** [comment]
i cant confirm it v0.3.8-21-gfd57d3e4 not working here

**Comment by cpasoft** [comment]
It still not working on 0.3.8-21. Rolled back again to -16 (b7b3148)

**Comment by CaryBab** [comment]
Still not working with 3.8.21 for my either.

**Comment by CaryBab** [comment]
I also rolled back, and that got my display back.  Thanks for posting that, did not know how to do that.

**Comment by Guilouz** [comment]
Should be ok now

**Comment by CaryBab** [comment]
OK.  I updated with 22, and it is indeed fixed.  Thanks Cyril.

**Comment by Winky1st** [comment]
I confirm! with 22 its working again.
Ty Cyril
